language: java
jdk:
  - openjdk8

branches: #branches: Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정
  only:
    - master

# Travis CI 서버의 Home
cache:  #cache: gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
  directories:
    - '$HOME/.m2/repositor'
    - '$HOME/.gradle'

script: "./gradlew clean build" #script: master 브랜치에 푸시되었을 때 수행하는 명령어

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jongtix@gmail.com

before_install:
  - chmod +x gradlew  #gradlew Permission denied 해결
                      #출처: https://m.blog.naver.com/PostView.nhn?blogId=ggomjae&logNo=221778504421&proxyReferer=https:%2F%2Fwww.google.com%2F
  - zip -r FirstProject FirstProject #현재 위치의 모든 파일을 FirstProject 이름으로 압축
  - mkdir -p deploy
  - mv FirstProject.zip deploy/FirstProject.zip

deploy: #S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY  #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY  #Travis repo settings에 설정된 값
    bucket: aws-firstproject-jongtix-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private  #zip 파일 접근을 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
                      #해당 위치의 파일들만 S3로 전송
    wait-until-deployed: true
