language: java
jdk:
  - openjdk8

branches: #branches: Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정
  only:
    - master

# Travis CI 서버의 Home
cache:  #cache: gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
  directories:
    - '$HOME/.m2/repositor'
    - '$HOME/.gradle'

script: "./gradlew clean build" #script: master 브랜치에 푸시되었을 때 수행하는 명령어

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jongtix@gmail.com